/**
 * Pair-voiced descriptions for the overall radar section in pair insights.
 * Keys match `getBrainCombination` combo labels (same as OVERALL_ARCHETYPES).
 * Voice: "this pair / they / their / between them" — not "you / your".
 */
export const PAIR_OVERALL_DESCRIPTIONS: Record<string, string> = {
  'Head Strong':
    "This pair leads with thinking. Their first move in any situation is to understand it together: gather information, weigh options, and build a shared picture before committing.\n\nThat shared analytical instinct creates real alignment. Others trust their reasoning and come to them when something needs to be thought through with care.\n\n**Thinking can become a place this pair stays rather than passes through.**\n\nWithout strong access to Gut or Heart in the pair, they may stall on incomplete information, miss the emotional temperature in the room, or delay the call until the case feels watertight. The tension between them is often about which angle to analyse next, not whether to act.\n\nThe question for this pair isn't whether their thinking is good; it usually is. It's whether they're letting it serve them, or using it together to avoid the discomfort of moving.",

  'Head + Gut':
    "This pair thinks clearly and acts boldly. They can assess a situation with rigour, then move on it with confidence, often before others have finished deliberating. That combination makes them highly effective across a wide range of demands.\n\n**What they may not see is the human layer.**\n\nBoth tend to trust analysis and instinct. When the pair doesn't attend to feeling, their best decisions can still land badly on the people involved. Speed and rigour are genuine strengths here; the gap is relational, not intellectual.\n\nThe work for this pair is building in a brief shared moment, even just one question, to ask what the human experience of a decision will be before they move.",

  'Head + Heart':
    "This pair thinks carefully and cares deeply. They bring both analytical rigour and genuine attentiveness to people. Together, they're likely to be thorough, considerate, and widely trusted.\n\n**The challenge is that Head and Heart together can create a shared loop.**\n\nThey analyse, check in on how people are doing, and without something to break the cycle, can stay in preparation longer than the situation needs. Bold, instinctive action may be harder to access between them, especially when a decision is unpopular or time is short.\n\nThe question for this pair is whether they're using their care and rigour to move well, or using them together to avoid moving at all.",

  'Heart Strong':
    "This pair leads with feeling. Their first response to any situation is relational: they notice how people are, what they need, and how things are landing emotionally.\n\n**That shared attentiveness is a real gift to the people around them.**\n\nWhat can be harder is holding a firm analytical position under pressure, or making a decisive call when the data is ambiguous. Together, they may also find they accommodate each other past the point that serves either of them, because discomfort in the relationship can feel more urgent than the thing that caused it.\n\nThe work for this pair is recognising that clarity and care aren't in conflict, and that sometimes the most caring move they can make is to say the direct thing.",

  'Heart + Gut':
    "This pair feels deeply and moves quickly. They're responsive, energising, and genuinely motivated by the people they work with, and they back that care with a shared willingness to act.\n\n**Others often experience them as warm, direct, and fully present.**\n\nThe challenge is that feeling and instinct together can move faster than thinking. They may commit before fully assessing, or act on what feels right without asking whether it's been thought through. Analytical rigour may also come slower here, not because they're incapable of it, but because it can feel slower or colder than how they naturally operate together.\n\nThe question for this pair is whether they're bringing enough structure to match their shared energy, so that what they're trying to do for people actually lands the way they intend.",

  'Heart + Head':
    "This pair leads with care and backs it with thinking. People come first for them, and once the relational ground feels solid, they bring genuine analytical depth to whatever they're working on.\n\n**Together, they tend to be trusted both as people and as thinkers.**\n\nThe challenge is that Heart first and Head second can mean a significant amount of shared energy goes toward making sure everyone is okay before they feel free to move. Their need for relational safety and analytical certainty can reinforce each other, giving both reasons to wait when the situation is calling for action.\n\nThe question for this pair isn't whether they care or think well. It's whether they're giving themselves permission to trust both enough to move.",

  'Gut Strong':
    "This pair leads with instinct. They read situations quickly, back their own judgment, and move with a shared confidence that others often find compelling. Between them, they don't need complete information to act.\n\n**Instinct without Head or Heart, shared between two people, can move faster than wisdom.**\n\nThey may act before fully understanding a situation, or make calls that are directionally right but land harder than needed because neither attended to the human dimension. When their instinct is challenged, the pair's first response may be confidence rather than curiosity, and that dynamic can reinforce itself.\n\nThe work for this pair is learning to distinguish between trusting themselves and closing themselves off, because one is a shared strength and the other is a shared risk.",

  'Gut + Head':
    "This pair acts boldly and thinks rigorously. Together, they're both decisive and credible. They make the call and can back it up, which means others tend to follow their direction and trust the ground they've covered.\n\n**They can be highly effective without being particularly warm.**\n\nOver time, that gap tends to show up in how people experience working with or around them, even when the outcomes are strong. The pair's shared instinct and analysis can land on people rather than with them.\n\nThe work for this pair is building in the relational awareness that makes their speed and rigour feel collaborative rather than directive.",

  'Gut + Heart':
    "This pair moves fast and cares genuinely. Together, they're energising, loyal, and highly responsive to the people around them.\n\n**They bring real presence to whatever they're doing, and others tend to feel it.**\n\nThe challenge is that instinct and feeling together can bypass thinking. They may commit quickly, underestimate complexity, or find themselves in situations that energy and care alone can't resolve. They're also more likely to over-extend, saying yes to too much because both the instinct to act and the desire to help are strong between them.\n\nThe question for this pair is whether they're bringing enough structure and analytical grounding to convert their shared energy into sustainable results, not just good intentions and momentum.",

  'Head + Heart + Gut':
    "This pair has access to all three centres: analytical depth, relational warmth, and instinctive confidence. That range is a genuine strength. Together, they can think, feel, and act, and have the capacity to navigate almost any kind of situation.\n\n**Having access to all three doesn't mean they work together naturally.**\n\nDifferent centres may pull in different directions, and under pressure the pair may default strongly to one and lose access to the others. Others can also find them harder to read, because there is no single dominant mode to anchor on.\n\nThe question for this pair isn't what they're missing. It's whether they're using what they have with intention, choosing which centre to lead from together rather than being pulled between them.",
}
