export { SectionResults } from './SectionResults'
export { SectionCard } from './SectionCard'
export { UnderPressure } from './UnderPressure/UnderPressure'
export { DoingWork } from './DoingWork/DoingWork'
export { WithPeople } from './WithPeople/WithPeople'
export { GettingBetter } from './GettingBetter/GettingBetter'
export { PressureProfile, getPressureProfileForScores, getBrainCombinationKey } from './UnderPressure/PressureProfile/PressureProfile.tsx'
export type { PressureProfileData } from './UnderPressure/PressureProfile/PressureProfile.tsx'
export { getBrainCombination, getBrainIcons, getTier, SECTION_ICONS } from './utils.tsx'
export type { AnswerType } from './utils.tsx'
