export { SectionResults } from './SectionResults'
export { SectionCard } from './SectionCard'
export { UnderPressure } from './Sections/UnderPressure'
export { DoingWork } from './Sections/DoingWork'
export { WithPeople } from './Sections/WithPeople'
export { GettingBetter } from './Sections/GettingBetter'
export { PressureProfileTable, getPressureProfileForScores } from './Tables/PressureProfileTable.tsx'
export type { PressureProfileData } from './Tables/PressureProfileTable.tsx'
export { getBrainCombination, getBrainCombinationKey, getBrainIcons, getTier, getBalanceTipBadge, SECTION_ICONS } from './utils.tsx'
export type { AnswerType } from './utils.tsx'
